### ISSUE TITLE
Job.groovy: arch vs kernel_arch

### ISSUE THREAD

**Issue by khilman** [kernelci/kernelci-core-staging#72]
Why is the function argument `kernel_arch` but the code using `arch` ?
https://github.com/kernelci/kernelci-core-staging/blob/bbc5e21fe90c2efec36f2b6c56a19516d0a06b60/src/org/kernelci/util/Job.groovy#L40

**Comment by gctucker** [comment]
That's a bug - the real question I have is how can this actually work...  I guess because Groovy.  I'll test a fix for that alongside other changes on my branch and make a PR.

**Comment by gctucker** [comment]
This was fixed a while ago.
